// Generate a PostgreSQL schema from the legacy MySQL DB by introspecting
// information_schema. Run from the prenodo/ dir (needs mysql2).
//
//   node db/tools/generate-schema.mjs > db/schema.sql
//
// Reads MySQL credentials from the legacy config.php (no secrets in repo).
// Design decisions (see docs/migration-roadmap.md §3.2):
//  - tinyint -> smallint   (preserve WHERE x=1 / x=0 semantics; no query churn)
//  - enum    -> text + CHECK (col IN (...))   (storage as string + validation)
//  - AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY (explicit ids on import OK)
//  - datetime/timestamp -> timestamp (no tz; PHP stored naive local times)
//  - ON UPDATE CURRENT_TIMESTAMP -> BEFORE UPDATE trigger
//  - per-table tenant_id BEFORE INSERT trigger reading current_setting('app.tenant_id')
//    (faithful port of the MySQL @app_tenant_id + bi_* triggers; the data layer
//     must `SET app.tenant_id` per connection — this is the multi-tenant safety net)
//  - all identifiers double-quoted in DDL (safe against reserved words)

import fs from "node:fs";
import mysql from "mysql2/promise";

const XAMPP = process.env.PRENODO_XAMPP_ROOT || "C:\\xampp\\htdocs";
function phpVal(src, key) {
  const m = src.match(new RegExp(`['"]${key}['"]\\s*=>\\s*['"]([^'"]*)['"]`));
  return m ? m[1] : null;
}
const cfgSrc = fs.readFileSync(`${XAMPP}/config.php`, "utf8");
const DB = phpVal(cfgSrc, "name");
const conn = await mysql.createConnection({
  host: phpVal(cfgSrc, "host") || "localhost",
  user: phpVal(cfgSrc, "user"),
  password: phpVal(cfgSrc, "pass") || "",
  database: DB,
});

const q = async (sql, args = []) => (await conn.query(sql, args))[0];
const qid = (s) => `"${s}"`;

// ---- collect tables ----
const tables = (await q(
  `SELECT table_name FROM information_schema.tables
   WHERE table_schema=? AND table_type='BASE TABLE' ORDER BY table_name`, [DB]
)).map((r) => r.TABLE_NAME ?? r.table_name);

// ---- type mapping ----
function pgType(c) {
  const dt = (c.DATA_TYPE || "").toLowerCase();
  const ct = (c.COLUMN_TYPE || "").toLowerCase();
  switch (dt) {
    case "tinyint": return "smallint";
    case "smallint": return "smallint";
    case "mediumint":
    case "int": return ct.includes("unsigned") ? "bigint" : "integer";
    case "bigint": return "bigint";
    case "decimal": {
      const p = c.NUMERIC_PRECISION ?? 10, s = c.NUMERIC_SCALE ?? 0;
      return `numeric(${p},${s})`;
    }
    case "double": return "double precision";
    case "float": return "real";
    case "char": return `char(${c.CHARACTER_MAXIMUM_LENGTH || 255})`;
    case "varchar": return `varchar(${c.CHARACTER_MAXIMUM_LENGTH || 255})`;
    case "tinytext":
    case "text":
    case "mediumtext":
    case "longtext": return "text";
    case "tinyblob":
    case "blob":
    case "mediumblob":
    case "longblob": return "bytea";
    case "date": return "date";
    case "time": return "time";
    case "datetime":
    case "timestamp": return "timestamp";
    case "json": return "jsonb";
    case "enum": return "text"; // + CHECK added separately
    default: throw new Error(`Unmapped type ${dt} (${ct})`);
  }
}

function enumValues(ct) {
  // enum('a','b','c')  -> ['a','b','c']
  const inner = ct.slice(ct.indexOf("(") + 1, ct.lastIndexOf(")"));
  const vals = [];
  let re = /'((?:[^'\\]|\\.|'')*)'/g, m;
  while ((m = re.exec(inner))) vals.push(m[1].replace(/''/g, "'").replace(/\\'/g, "'"));
  return vals;
}

function defaultClause(c, pgt) {
  const dt = (c.DATA_TYPE || "").toLowerCase();
  let d = c.COLUMN_DEFAULT;
  if (d === null || d === undefined) return "";
  const ds = String(d).trim();
  if (/^(current_timestamp(\(\))?|now\(\))$/i.test(ds)) return "DEFAULT CURRENT_TIMESTAMP";
  if (ds.toUpperCase() === "NULL") return "";
  const numeric = ["smallint", "integer", "bigint", "double precision", "real"].includes(pgt) || pgt.startsWith("numeric");
  if (numeric) {
    const n = ds.replace(/^'(.*)'$/, "$1");
    if (n === "") return "";
    return `DEFAULT ${n}`;
  }
  // string/enum/date/text: ensure single-quoted
  let v = ds;
  if (/^'.*'$/.test(v)) v = v.slice(1, -1);
  v = v.replace(/'/g, "''");
  return `DEFAULT '${v}'`;
}

// ---- build per-table DDL ----
const out = [];
out.push(`-- Generated from MySQL '${DB}' by db/tools/generate-schema.mjs`);
out.push(`-- ${tables.length} tables. Do not edit by hand; regenerate.`);
out.push(`SET client_min_messages = warning;`);
out.push(`SET search_path = public;`);
out.push("");

const indexStmts = [];
const tenantTables = [];
const onUpdate = []; // {table, col}
const usedIndexNames = new Set();

for (const t of tables) {
  const cols = await q(
    `SELECT * FROM information_schema.columns
     WHERE table_schema=? AND table_name=? ORDER BY ORDINAL_POSITION`, [DB, t]
  );
  const lines = [];
  let hasTenant = false;
  for (const c of cols) {
    const name = c.COLUMN_NAME;
    if (name === "tenant_id") hasTenant = true;
    if (c.EXTRA && /on update/i.test(c.EXTRA)) onUpdate.push({ table: t, col: name });

    // generated column
    if (c.GENERATION_EXPRESSION && String(c.GENERATION_EXPRESSION).trim() !== "") {
      let expr = String(c.GENERATION_EXPRESSION)
        .replace(/`/g, '"')
        .replace(/\bifnull\b/gi, "COALESCE");
      lines.push(`  ${qid(name)} ${pgType(c)} GENERATED ALWAYS AS (${expr}) STORED`);
      continue;
    }

    const pgt = pgType(c);
    let line = `  ${qid(name)} ${pgt}`;
    if ((c.EXTRA || "").toLowerCase().includes("auto_increment")) {
      line = `  ${qid(name)} ${pgt === "bigint" ? "bigint" : "integer"} GENERATED BY DEFAULT AS IDENTITY`;
    } else {
      const def = defaultClause(c, pgt);
      if (def) line += ` ${def}`;
    }
    if (c.IS_NULLABLE === "NO" && !(c.EXTRA || "").toLowerCase().includes("auto_increment")) {
      // identity is implicitly not null; others honour nullability
      line += " NOT NULL";
    } else if (c.IS_NULLABLE === "NO") {
      line += " NOT NULL";
    }
    if ((c.DATA_TYPE || "").toLowerCase() === "enum") {
      const vals = enumValues(c.COLUMN_TYPE).map((v) => `'${v.replace(/'/g, "''")}'`).join(", ");
      line += ` CHECK (${qid(name)} IN (${vals}))`;
    }
    lines.push(line);
  }
  if (hasTenant) tenantTables.push(t);

  // indexes
  const stats = await q(
    `SELECT INDEX_NAME, NON_UNIQUE, SEQ_IN_INDEX, COLUMN_NAME
     FROM information_schema.statistics
     WHERE table_schema=? AND table_name=? ORDER BY INDEX_NAME, SEQ_IN_INDEX`, [DB, t]
  );
  const byIdx = new Map();
  for (const s of stats) {
    if (!byIdx.has(s.INDEX_NAME)) byIdx.set(s.INDEX_NAME, { unique: s.NON_UNIQUE === 0, cols: [] });
    byIdx.get(s.INDEX_NAME).cols.push(s.COLUMN_NAME);
  }
  for (const [iname, info] of byIdx) {
    const colList = info.cols.map(qid).join(", ");
    if (iname === "PRIMARY") {
      lines.push(`  PRIMARY KEY (${colList})`);
    } else {
      let nm = `${t}_${iname}`;
      if (nm.length > 60) nm = nm.slice(0, 54) + "_" + (usedIndexNames.size);
      while (usedIndexNames.has(nm)) nm += "_x";
      usedIndexNames.add(nm);
      indexStmts.push(`CREATE ${info.unique ? "UNIQUE " : ""}INDEX ${qid(nm)} ON ${qid(t)} (${colList});`);
    }
  }

  out.push(`CREATE TABLE ${qid(t)} (`);
  out.push(lines.join(",\n"));
  out.push(`);`);
  out.push("");
}

// ---- indexes ----
out.push("-- Secondary indexes");
out.push(...indexStmts);
out.push("");

// ---- triggers: tenant_id safety net ----
out.push("-- Multi-tenant safety net: fill tenant_id from app.tenant_id GUC on insert");
out.push(`CREATE OR REPLACE FUNCTION app_set_tenant_id() RETURNS trigger AS $$
BEGIN
  IF NEW.tenant_id IS NULL OR NEW.tenant_id = 0 THEN
    NEW.tenant_id := COALESCE(NULLIF(current_setting('app.tenant_id', true), '')::int, 0);
  END IF;
  RETURN NEW;
END; $$ LANGUAGE plpgsql;`);
for (const t of tenantTables) {
  out.push(`CREATE TRIGGER ${qid("bi_" + t + "_tenant_id")} BEFORE INSERT ON ${qid(t)} FOR EACH ROW EXECUTE FUNCTION app_set_tenant_id();`);
}
out.push("");

// ---- triggers: ON UPDATE CURRENT_TIMESTAMP ----
const touchCols = [...new Set(onUpdate.map((x) => x.col))];
out.push("-- ON UPDATE CURRENT_TIMESTAMP replacement triggers");
for (const col of touchCols) {
  out.push(`CREATE OR REPLACE FUNCTION ${qid("app_touch_" + col)}() RETURNS trigger AS $$
BEGIN NEW.${qid(col)} := CURRENT_TIMESTAMP; RETURN NEW; END; $$ LANGUAGE plpgsql;`);
}
for (const { table, col } of onUpdate) {
  out.push(`CREATE TRIGGER ${qid("bu_" + table + "_" + col)} BEFORE UPDATE ON ${qid(table)} FOR EACH ROW EXECUTE FUNCTION ${qid("app_touch_" + col)}();`);
}
out.push("");

await conn.end();
process.stdout.write(out.join("\n"));
process.stderr.write(`\nGenerated DDL: ${tables.length} tables, ${indexStmts.length} indexes, ${tenantTables.length} tenant triggers, ${onUpdate.length} updated-at triggers\n`);
