// Registro attività operatori ("Log", feature approvata 2026-07-16): traccia
// curata delle mutazioni (crea/modifica/elimina/annulla + login) su tutti i
// moduli, con retention 30 giorni e pulizia opportunistica (nessun cron).
// - logActivity è FIRE-AND-FORGET: non deve MAI far fallire l'operazione che
//   registra (catch totale, fuori dalle transazioni di business).
// - user_label è uno SNAPSHOT (nome || email || #id): la voce resta leggibile
//   anche se l'operatore viene rinominato o eliminato.
// - La verifica post-DDL usa information_schema DIRETTO (mai tableExists/
//   columnExists dopo una CREATE: la loro cache resterebbe avvelenata).
import { businessNowDateTime } from "@/lib/business-datetime";
import { dbExecute, dbQuery, quoteIdentifier, tenantTable, type RowDataPacket } from "@/lib/tenant-db";

export const ACTIVITY_LOG_RETENTION_DAYS = 30;
export const ACTIVITY_LOG_PAGE_SIZE = 25;

export type ActivityUser = { id?: number; email?: string; name?: string } | null | undefined;

export type ActivityEntry = {
  user: ActivityUser;
  locationId?: number;
  module: string;
  action: string;
  entityType?: string;
  entityId?: number;
  label: string;
  details?: unknown;
};

export type ActivityLogRow = {
  id: number;
  createdAt: string;
  userId: number;
  userLabel: string;
  locationId: number;
  module: string;
  action: string;
  entityType: string;
  entityId: number;
  label: string;
  details: string;
};

const readyTables = new Set<string>();
let lastPurgeAt = 0;

function userLabelOf(user: ActivityUser): string {
  const name = String(user?.name ?? "").trim();
  if (name !== "") return name;
  const email = String(user?.email ?? "").trim();
  if (email !== "") return email;
  const id = Number(user?.id ?? 0) || 0;
  return id > 0 ? `#${id}` : "—";
}

async function ensureActivityTable(slug: string): Promise<{ name: string; tenantId: number } | null> {
  try {
    const t = await tenantTable(slug, "activity_logs");
    if (readyTables.has(t.name)) return { name: t.name, tenantId: t.tenantId ?? 0 };
    await dbExecute(
      `CREATE TABLE IF NOT EXISTS ${quoteIdentifier(t.name)} (
        tenant_id INT NOT NULL,
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP NOT NULL,
        user_id INT NULL,
        user_label TEXT NOT NULL DEFAULT '',
        location_id INT NULL,
        module TEXT NOT NULL,
        action TEXT NOT NULL,
        entity_type TEXT NULL,
        entity_id INT NULL,
        label TEXT NOT NULL,
        details_json TEXT NULL
      )`,
    ).catch(() => undefined);
    await dbExecute(
      `CREATE INDEX IF NOT EXISTS ${quoteIdentifier(`${t.name}_tenant_created_idx`)} ON ${quoteIdentifier(t.name)} (tenant_id, created_at DESC)`,
    ).catch(() => undefined);
    const rows = await dbQuery<RowDataPacket[]>(
      "SELECT 1 AS ok FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = ?",
      [t.name],
    ).catch(() => [] as RowDataPacket[]);
    if (!rows[0]) return null;
    readyTables.add(t.name);
    return { name: t.name, tenantId: t.tenantId ?? 0 };
  } catch {
    return null;
  }
}

// Purge opportunistica (throttle 1h per processo): elimina le voci più vecchie
// della retention. Best-effort come tutto il resto.
async function purgeOldEntries(table: { name: string; tenantId: number }, force = false): Promise<void> {
  const now = Date.now();
  if (!force && now - lastPurgeAt < 60 * 60 * 1000) return;
  lastPurgeAt = now;
  // Cutoff in ORA DI ROMA (server-TZ-safe, classe TZ fix 17/07): created_at è
  // wall-time Roma, un Date passato al driver userebbe il fuso del SERVER.
  const cutoff = businessNowDateTime(new Date(now - ACTIVITY_LOG_RETENTION_DAYS * 24 * 60 * 60 * 1000));
  await dbExecute(`DELETE FROM ${quoteIdentifier(table.name)} WHERE tenant_id = ? AND created_at < ?`, [table.tenantId, cutoff]).catch(() => undefined);
}

export async function logActivity(slug: string, entry: ActivityEntry): Promise<void> {
  try {
    const table = await ensureActivityTable(slug);
    if (!table) return;
    const details = entry.details === undefined || entry.details === null ? null : JSON.stringify(entry.details).slice(0, 4000);
    await dbExecute(
      `INSERT INTO ${quoteIdentifier(table.name)} (tenant_id, created_at, user_id, user_label, location_id, module, action, entity_type, entity_id, label, details_json) VALUES (?,?,?,?,?,?,?,?,?,?,?)`,
      [
        table.tenantId,
        // Wall-time di ROMA esplicito (server-TZ-safe): con new Date() il
        // driver serializzerebbe nel fuso del server (UTC su Amplify).
        businessNowDateTime(),
        Number(entry.user?.id ?? 0) || null,
        userLabelOf(entry.user),
        Number(entry.locationId ?? 0) || null,
        String(entry.module ?? "").slice(0, 60),
        String(entry.action ?? "").slice(0, 40),
        entry.entityType ? String(entry.entityType).slice(0, 60) : null,
        Number(entry.entityId ?? 0) || null,
        String(entry.label ?? "").slice(0, 500),
        details,
      ],
    );
    void purgeOldEntries(table);
  } catch {
    // fire-and-forget: mai propagare
  }
}

export type ActivityLogFilters = {
  module?: string;
  action?: string;
  userLabel?: string;
  q?: string;
  page?: number;
  // Restrizione per-SEDE (non-admin con logs.view, [[sede-access-model]]):
  // vuoto = tutte; altrimenti solo le voci delle sedi indicate + quelle senza
  // sede (location_id NULL, es. salvataggi di configurazione globali).
  locationIds?: number[];
};

export type ActivityLogList = {
  rows: ActivityLogRow[];
  totalCount: number;
  pageSize: number;
  currentPage: number;
  modules: string[];
  actions: string[];
  users: string[];
};

export async function listActivityLogs(slug: string, filters: ActivityLogFilters = {}): Promise<ActivityLogList> {
  const empty: ActivityLogList = { rows: [], totalCount: 0, pageSize: ACTIVITY_LOG_PAGE_SIZE, currentPage: 1, modules: [], actions: [], users: [] };
  const table = await ensureActivityTable(slug);
  if (!table) return empty;
  await purgeOldEntries(table, true);

  const clauses: string[] = ["tenant_id = ?"];
  const params: unknown[] = [table.tenantId];
  const mod = String(filters.module ?? "").trim();
  if (mod !== "") {
    clauses.push("module = ?");
    params.push(mod);
  }
  const act = String(filters.action ?? "").trim();
  if (act !== "") {
    clauses.push("action = ?");
    params.push(act);
  }
  const usr = String(filters.userLabel ?? "").trim();
  if (usr !== "") {
    clauses.push("user_label = ?");
    params.push(usr);
  }
  const q = String(filters.q ?? "").trim();
  if (q !== "") {
    const like = `%${q.replace(/!/g, "!!").replace(/%/g, "!%").replace(/_/g, "!_")}%`;
    clauses.push("(label ILIKE ? ESCAPE '!' OR user_label ILIKE ? ESCAPE '!')");
    params.push(like, like);
  }
  const allowedLocs = (filters.locationIds ?? []).map((n) => Number(n) || 0).filter((n) => n > 0);
  if (allowedLocs.length > 0) {
    clauses.push(`(location_id IS NULL OR location_id IN (${allowedLocs.map(() => "?").join(",")}))`);
    params.push(...allowedLocs);
  }
  const where = clauses.join(" AND ");
  const page = Math.max(1, Math.floor(Number(filters.page ?? 1) || 1));
  // Scope tenant+sede per i DISTINCT dei filtri (senza gli altri criteri).
  const locScopeWhere = allowedLocs.length > 0 ? `tenant_id = ? AND (location_id IS NULL OR location_id IN (${allowedLocs.map(() => "?").join(",")}))` : "tenant_id = ?";
  const locScopeParams = allowedLocs.length > 0 ? [table.tenantId, ...allowedLocs] : [table.tenantId];

  const [rows, countRows, moduleRows, actionRows, userRows] = await Promise.all([
    dbQuery<RowDataPacket[]>(
      `SELECT id, created_at, user_id, user_label, location_id, module, action, entity_type, entity_id, label, details_json FROM ${quoteIdentifier(table.name)} WHERE ${where} ORDER BY created_at DESC, id DESC LIMIT ${ACTIVITY_LOG_PAGE_SIZE} OFFSET ${(page - 1) * ACTIVITY_LOG_PAGE_SIZE}`,
      params,
    ),
    dbQuery<RowDataPacket[]>(`SELECT COUNT(*) AS n FROM ${quoteIdentifier(table.name)} WHERE ${where}`, params),
    // Anche i DISTINCT dei filtri rispettano la restrizione per-sede (un
    // operatore ristretto non deve vedere moduli/operatori di altre sedi).
    dbQuery<RowDataPacket[]>(`SELECT DISTINCT module FROM ${quoteIdentifier(table.name)} WHERE ${locScopeWhere} ORDER BY module`, locScopeParams),
    dbQuery<RowDataPacket[]>(`SELECT DISTINCT action FROM ${quoteIdentifier(table.name)} WHERE ${locScopeWhere} ORDER BY action`, locScopeParams),
    dbQuery<RowDataPacket[]>(`SELECT DISTINCT user_label FROM ${quoteIdentifier(table.name)} WHERE ${locScopeWhere} ORDER BY user_label`, locScopeParams),
  ]);

  // I timestamp arrivano come stringhe locali (setTypeParser del tenant-db):
  // si rimappano al formato "YYYY-MM-DD HH:MM:SS" senza shift di timezone.
  const localOrEmpty = (v: unknown): string => {
    if (!v) return "";
    if (v instanceof Date) {
      const pad = (n: number) => String(n).padStart(2, "0");
      return `${v.getFullYear()}-${pad(v.getMonth() + 1)}-${pad(v.getDate())} ${pad(v.getHours())}:${pad(v.getMinutes())}:${pad(v.getSeconds())}`;
    }
    return String(v).slice(0, 19).replace("T", " ");
  };

  return {
    rows: rows.map((r) => ({
      id: Number(r.id) || 0,
      createdAt: localOrEmpty(r.created_at),
      userId: Number(r.user_id ?? 0) || 0,
      userLabel: String(r.user_label ?? ""),
      locationId: Number(r.location_id ?? 0) || 0,
      module: String(r.module ?? ""),
      action: String(r.action ?? ""),
      entityType: String(r.entity_type ?? ""),
      entityId: Number(r.entity_id ?? 0) || 0,
      label: String(r.label ?? ""),
      details: String(r.details_json ?? ""),
    })),
    totalCount: Number(countRows[0]?.n ?? 0) || 0,
    pageSize: ACTIVITY_LOG_PAGE_SIZE,
    currentPage: page,
    modules: moduleRows.map((r) => String(r.module ?? "")).filter(Boolean),
    actions: actionRows.map((r) => String(r.action ?? "")).filter(Boolean),
    users: userRows.map((r) => String(r.user_label ?? "")).filter(Boolean),
  };
}
